"""Fetch each job site's real favicon and bake it into src/lib/logos.js.

Run once (or when a connector is added):
    .venv\\Scripts\\python.exe tools\\fetch_logos.py

Why data URIs rather than files: the packaged app loads its UI over file://,
where absolute asset paths break, and the CSP blocks remote images. Inlining the
icons sidesteps both and keeps the app working offline.

Sites are tried in order: the page's declared <link rel="icon">, then the
conventional /favicon.ico. Anything that fails is simply left out — the UI falls
back to a coloured monogram for that site.
"""
import base64
import json
import re
import sys
from pathlib import Path

from curl_cffi import requests as cr

SITES = {
    "naukrigulf": "https://www.naukrigulf.com/",
    "linkedin": "https://www.linkedin.com/",
    # bayt.com root declares no icons and serves a 204 for /favicon.ico; the
    # localised page is the one carrying the CDN <link rel="icon"> tags
    "bayt": "https://www.bayt.com/en/uae/",
    "indeed": "https://www.indeed.com/",
    "gulftalent": "https://www.gulftalent.com/",
    "emirates": "https://www.emiratesgroupcareers.com/",
    "sap": "https://jobs.sap.com/",
    "amazon": "https://www.amazon.jobs/",
    "oracle": "https://www.oracle.com/",
    "greenhouse": "https://www.greenhouse.io/",
    "smartrecruiters": "https://www.smartrecruiters.com/",
    "ashby": "https://jobs.ashbyhq.com/",
}

ICON_RE = re.compile(
    r'<link[^>]+rel=["\'][^"\']*icon[^"\']*["\'][^>]*>', re.I)
HREF_RE = re.compile(r'href=["\']([^"\']+)["\']', re.I)
SIZE_RE = re.compile(r'sizes=["\'](\d+)', re.I)

MIME = {"png": "image/png", "ico": "image/x-icon", "svg": "image/svg+xml",
        "jpg": "image/jpeg", "jpeg": "image/jpeg", "gif": "image/gif"}
MAX_BYTES = 60_000          # keep the generated module small


def get(url, **kw):
    try:
        r = cr.get(url, impersonate="chrome", timeout=20, **kw)
        return r if r.status_code == 200 and r.content else None
    except Exception:
        return None


def absolutise(href: str, base: str) -> str:
    if href.startswith("//"):
        return "https:" + href
    if href.startswith("http"):
        return href
    root = "/".join(base.split("/")[:3])
    return root + ("" if href.startswith("/") else "/") + href


def get_page(url):
    """Like get(), but keeps 404 bodies: single-page apps serve their real
    <head> (icons included) on a 404 route, which is all we need here."""
    try:
        r = cr.get(url, impersonate="chrome", timeout=20)
        return r if r.text else None
    except Exception:
        return None


def best_icon(site_url: str) -> str | None:
    """Prefer the largest declared PNG; fall back to /favicon.ico."""
    page = get_page(site_url)
    candidates = []
    if page:
        html = page.text[:200_000]
        for tag in ICON_RE.findall(html):
            m = HREF_RE.search(tag)
            if not m:
                continue
            size = int(SIZE_RE.search(tag).group(1)) if SIZE_RE.search(tag) else 0
            href = absolutise(m.group(1), page.url if hasattr(page, "url") else site_url)
            # a 180px apple-touch-icon looks far better than a 16px .ico
            candidates.append((0 if href.endswith(".svg") else 1, -size, href))
    candidates.sort()
    ordered = [c[2] for c in candidates] + [absolutise("/favicon.ico", site_url)]

    for href in ordered:
        r = get(href)
        if not r or len(r.content) > MAX_BYTES:
            continue
        ext = href.rsplit(".", 1)[-1].split("?")[0].lower()
        mime = MIME.get(ext) or r.headers.get("content-type", "").split(";")[0]
        if not mime.startswith("image"):
            continue
        return f"data:{mime};base64," + base64.b64encode(r.content).decode()
    return None


def main() -> None:
    out, missing = {}, []
    for key, url in SITES.items():
        icon = best_icon(url)
        if icon:
            out[key] = icon
            print(f"  {key:16} ok  ({len(icon) // 1024} KB)")
        else:
            missing.append(key)
            print(f"  {key:16} -- no icon, will use monogram")

    target = Path(__file__).resolve().parents[2] / "src" / "lib" / "logos.js"
    body = ",\n".join(f'  {k}: "{v}"' for k, v in out.items())
    target.write_text(
        "// Generated by backend/tools/fetch_logos.py — do not edit by hand.\n"
        "// Site favicons inlined as data URIs so they render offline and under file://.\n"
        f"export const LOGOS = {{\n{body}\n}};\n",
        encoding="utf-8",
    )
    print(f"\nwrote {target}  ({len(out)} logos, {target.stat().st_size // 1024} KB)")
    if missing:
        print("missing:", ", ".join(missing))


if __name__ == "__main__":
    sys.exit(main())
